name: test

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 2
      MKL_NUM_THREADS: 2
      OPENBLAS_NUM_THREADS: 2

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pwd
        env
        echo OPENBLAS_NUM_THREADS: $OPENBLAS_NUM_THREADS
    - name: tmate
      run: |
        pwd
        cd ..
        pwd
        ls -ltrah
        which bash
        bash start-tmate.sh
