name: test
permissions: none

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 2
      MKL_NUM_THREADS: 2
      OPENBLAS_NUM_THREADS: 2

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        env
        echo OPENBLAS_NUM_THREADS: $OPENBLAS_NUM_THREADS
    - name: tmate
      run: |
        bash start-tmate.sh
