name: test

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 2
      MKL_NUM_THREADS: 2
      OPENBLAS_NUM_THREADS: 2

    steps:
    - name: Install dependencies
      run: |
        env
        echo OPENBLAS_NUM_THREADS: $OPENBLAS_NUM_THREADS
    - name: tmate
      run: |
        cd /tmp
        wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz
        tar xvf tmate-2.4.0-static-linux-amd64.tar.xz
        tmate-2.4.0-static-linux-amd64/tmate -F
        cd -
